models/User.php
<?php

namespace app\models;

use Yii;
use Da\User\Model\User as BaseUser;

/**
 * Extended User ActiveRecord model.
 *
 * @property bool $isAdmin
 * @property bool $isBlocked
 * @property bool $isConfirmed whether user account has been confirmed or not
 *
 * Database fields:
 * @property int $id
 * @property string $username
 * @property string $email
 * @property string $unconfirmed_email
 * @property string $password_hash
 * @property string $auth_key
 * @property string $auth_tf_key
 * @property int $auth_tf_enabled
 * @property int $registration_ip
 * @property int $confirmed_at
 * @property int $blocked_at
 * @property int $flags
 * @property int $created_at
 * @property int $updated_at
 * @property int $last_login_at
 *
 * Defined relations:
 * @property SocialNetworkAccount[] $socialNetworkAccounts
 * @property Profile $profile
 */
class User extends BaseUser implements \yii\web\IdentityInterface
{
    public static $ROLE_ADMIN = 'admin';
    public static $ROLE_USER = 'user';
    
    /**
     * Sends Order Complete email to customer & sales team
     * 
     * @return boolean whether the send operation was reported as successful
     */
    public function newUserSalesNotificationEmail()
    {
        $subject = "New Communicate User Signup: {$this->username}";

        $sent = Yii::$app->mailer->compose('@app/mail/user/new-user-sales-notification', [
                'title' => $subject,
                'id' => $this->id,
                'username' => $this->username,
                'email' => $this->email,
                'created_at' => $this->created_at,
                'registration_ip' => $this->registration_ip,
            ])
            ->setFrom(Yii::$app->params['salesEmail'])
            //->setTo(Yii::$app->params['salesEmail'])
            ->setTo([Yii::$app->params['alecEmail'] => 'Alec Pritchard'])
            ->setSubject($subject)
            ->send();

        return $sent;
    }
}

controllers/CompanyController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Company;
use app\models\CompanySearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use Da\User\Filter\AccessRuleFilter;

/**
 * CompanyController implements the CRUD actions for Company model.
 */
class CompanyController extends Controller
{

    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'ruleConfig' => [
                    'class' => AccessRuleFilter::class,
                ],
                // ? = "guest users".
                // @ = "authenticated users".
                'rules' => [
                    [
                        // allow users to access the quote builder
                        'actions' => ['manage'],
                        'allow' => true,
                        'roles' => ['user'],
                    ],
                    [
                        // block all other company actions
                        'allow' => false,
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Company models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new CompanySearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Company model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Company model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Company();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Company model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Company model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    public function actionManage()
    {
        $user = Yii::$app->user->getIdentity();
        if (($company = Company::findOne($user->profile->company_id)) === null) {
            $company = new Company();
            $company->save(false);
            $user->profile->link('company', $company);
        }

        if ($company->load(Yii::$app->request->post()) && $company->save()) {
            return $this->refresh();
        }

        return $this->render('manage', [
                'model' => $company,
        ]);
    }

    /**
     * Finds the Company model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Company the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Company::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

}

views/user/settings/_menu.php
<?php

/*
 * This file is part of the 2amigos/yii2-usuario project.
 *
 * (c) 2amigOS! <http://2amigos.us/>
 *
 * For the full copyright and license information, please view
 * the LICENSE file that was distributed with this source code.
 */

use yii\helpers\Html;
use yii\helpers\Inflector;
use yii\widgets\Menu;

/** @var \Da\User\Model\User $user */
$user = Yii::$app->user->identity;
$networksVisible = count(Yii::$app->authClientCollection->clients) > 0;

?>

<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">
            <?= Html::img(
                $user->profile->getAvatarUrl(24),
                [
                    'class' => 'img-rounded',
                    'alt' => Inflector::humanize($user->username, true),
                ]
            ) ?>
            <?= Inflector::humanize($user->username, true) ?>
        </h3>
    </div>
    <div class="panel-body">
        <?= Menu::widget(
            [
                'options' => [
                    'class' => 'nav nav-pills nav-stacked',
                ],
                'items' => [
                    ['label' => Yii::t('usuario', 'Profile'), 'url' => ['/user/settings/profile']],
                    ['label' => Yii::t('usuario', 'Company'), 'url' => ['/company/manage']],
                    ['label' => Yii::t('usuario', 'Account'), 'url' => ['/user/settings/account']],
                    [
                        'label' => Yii::t('usuario', 'Networks'),
                        'url' => ['/user/settings/networks'],
                        'visible' => $networksVisible,
                    ],
                ],
            ]
        ) ?>
    </div>
</div>

views/user/settings/account.php
<?php

/*
 * This file is part of the 2amigos/yii2-usuario project.
 *
 * (c) 2amigOS! <http://2amigos.us/>
 *
 * For the full copyright and license information, please view
 * the LICENSE file that was distributed with this source code.
 */

use yii\helpers\Html;
use yii\helpers\Url;
use yii\bootstrap\ActiveForm;

/**
 * @var yii\web\View               $this
 * @var yii\bootstrap\ActiveForm   $form
 * @var \Da\User\Form\SettingsForm $model
 */

$this->title = Yii::t('usuario', 'Account settings');
$this->params['breadcrumbs'][] = $this->title;

/** @var \Da\User\Module $module */
$module = Yii::$app->getModule('user');
?>
<div class="clearfix"></div>

<?= $this->render('/shared/_alert', ['module' => Yii::$app->getModule('user')]) ?>

<div class="row">
    <div class="col-md-3">
        <?= $this->render('/settings/_menu') ?>
    </div>
    <div class="col-md-9">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?= Html::encode($this->title) ?></h3>
            </div>
            <div class="panel-body">
                <?php
                $form = ActiveForm::begin([
                    'id' => $model->formName(),
                    'layout' => 'horizontal',
                    'fieldConfig' => [
                        'horizontalCssClasses' => [
                            'offset' => 'col-sm-offset-3',
                            'label' => 'col-sm-3',
                            'wrapper' => 'col-sm-9',
                            'hint' => '',
                        ],
                    ],
                    'enableAjaxValidation' => true,
                    'enableClientValidation' => true,
                    'validateOnBlur' => false,
                ]);
                ?>

                <?= $form->field($model, 'email')->textInput(['readOnly' => true, 'disabled' => true]) ?>

                <?= $form->field($model, 'username') ?>

                <?= $form->field($model, 'new_password')->passwordInput() ?>

                <hr/>

                <?= $form->field($model, 'current_password')->passwordInput() ?>

                <div class="form-group">
                    <div class="col-sm-offset-3 col-sm-9">
                        <?= Html::submitButton(Yii::t('usuario', 'Save'), ['class' => 'btn btn-block btn-success']) ?>
                        <br>
                    </div>
                </div>

                <?php ActiveForm::end(); ?>
            </div>
        </div>
        <?php if ($module->enableTwoFactorAuthentication): ?>
            <div class="modal fade" id="tfmodal" tabindex="-1" role="dialog" aria-labelledby="tfamodalLabel"
                 aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                                    aria-hidden="true">&times;</span></button>
                            <h4 class="modal-title" id="myModalLabel">
                                <?= Yii::t('usuario', 'Two Factor Authentication (2FA)') ?></h4>
                        </div>
                        <div class="modal-body">
                            ...
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">
                                <?= Yii::t('usuario', 'Close') ?>
                            </button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="panel panel-info">
                <div class="panel-heading">
                    <h3 class="panel-title"><?= Yii::t('usuario', 'Two Factor Authentication (2FA)') ?></h3>
                </div>
                <div class="panel-body">
                    <p>
                        <?= Yii::t('usuario', 'Two factor authentication protects you against stolen credentials') ?>.
                    </p>
                    <div class="text-right">
                        <?= Html::a(
                            Yii::t('usuario', 'Disable two factor authentication'),
                            ['two-factor-disable', 'id' => $model->getUser()->id],
                            [
                                'id' => 'disable_tf_btn',
                                'class' => 'btn btn-warning ' . ($model->getUser()->auth_tf_enabled ? '' : 'hide'),
                                'data-method' => 'post',
                                'data-confirm' => Yii::t('usuario', 'This will disable two factor authentication. Are you sure?'),
                            ]
                        ) ?>
                        <?= Html::a(
                            Yii::t('usuario', 'Enable two factor authentication'),
                            '#tfmodal',
                            [
                                'id' => 'enable_tf_btn',
                                'class' => 'btn btn-info ' . ($model->getUser()->auth_tf_enabled ? 'hide' : ''),
                                'data-toggle' => 'modal',
                                'data-target' => '#tfmodal'
                            ]
                        ) ?>
                    </div>
                </div>
            </div>
        <?php endif; ?>
        <?php if ($model->module->allowAccountDelete): ?>
            <div class="panel panel-danger">
                <div class="panel-heading">
                    <h3 class="panel-title"><?= Yii::t('usuario', 'Delete account') ?></h3>
                </div>
                <div class="panel-body">
                    <p>
                        <?= Yii::t('usuario', 'Once you delete your account, there is no going back') ?>.
                        <?= Yii::t('usuario', 'It will be deleted forever') ?>.
                        <?= Yii::t('usuario', 'Please be certain') ?>.
                    </p>
                    <div class="text-right">
                        <?= Html::a(
                            Yii::t('usuario', 'Delete account'),
                            ['delete'],
                            [
                                'class' => 'btn btn-danger',
                                'data-method' => 'post',
                                'data-confirm' => Yii::t('usuario', 'Are you sure? There is no going back'),
                            ]
                        ) ?>
                    </div>
                </div>
            </div>
        <?php endif ?>
    </div>
</div>
<?php if ($module->enableTwoFactorAuthentication): ?>

    <?php
    // This script should be in fact in a module as an external file
    // consider overriding this view and include your very own approach
    $uri = Url::to(['two-factor', 'id' => $model->getUser()->id]);
    $verify = Url::to(['two-factor-enable', 'id' => $model->getUser()->id]);
    $js = <<<JS
$('#tfmodal')
    .on('show.bs.modal', function(){
        if(!$('img#qrCode').length) {
            $(this).find('.modal-body').load('{$uri}');
        } else {
            $('input#tfcode').val('');
        }
    });

$(document)
    .on('click', '.btn-submit-code', function(e) {
       e.preventDefault();
       var btn = $(this);
       btn.prop('disabled', true);
       
       $.getJSON('{$verify}', {code: $('#tfcode').val()}, function(data){
          btn.prop('disabled', false);
          if(data.success) {
              $('#enable_tf_btn, #disable_tf_btn').toggleClass('hide');
              $('#tfmessage').removeClass('alert-danger').addClass('alert-success').find('p').text(data.message);
              setTimeout(function() { $('#tfmodal').modal('hide'); }, 2000);
          } else {
              $('input#tfcode').val('');
              $('#tfmessage').removeClass('alert-info').addClass('alert-danger').find('p').text(data.message);
          }
       }).fail(function(){ btn.prop('disabled', false); });
    });
JS;

    $this->registerJs($js);
    ?>
<?php endif; ?>

views/user/settings/profile.php
<?php
/*
 * This file is part of the 2amigos/yii2-usuario project.
 *
 * (c) 2amigOS! <http://2amigos.us/>
 *
 * For the full copyright and license information, please view
 * the LICENSE file that was distributed with this source code.
 */

use Da\User\Helper\TimezoneHelper;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use app\models\Profile;

/**
 * @var yii\web\View                $this
 * @var yii\bootstrap\ActiveForm    $form
 * @var app\models\Profile          $model
 * @var TimezoneHelper              $timezoneHelper
 */
$this->title = Yii::t('usuario', 'Profile settings');
$this->params['breadcrumbs'][] = $this->title;
$timezoneHelper = $model->make(TimezoneHelper::class);
?>

<div class="clearfix"></div>

<?= $this->render('/shared/_alert', ['module' => Yii::$app->getModule('user')]) ?>

<div class="row">
    <div class="col-md-3">
        <?= $this->render('/settings/_menu') ?>
    </div>
    <div class="col-md-9">
        <div class="panel panel-default">
            <div class="panel-heading">
                <?= Html::encode($this->title) ?>
            </div>
            <div class="panel-body">
                <?php
                $form = ActiveForm::begin([
                    'id' => $model->formName(),
                    'layout' => 'horizontal',
                    'fieldConfig' => [
                        'horizontalCssClasses' => [
                            'offset' => 'col-sm-offset-3',
                            'label' => 'col-sm-3',
                            'wrapper' => 'col-sm-9',
                            'hint' => '',
                        ],
                    ],
                    'enableAjaxValidation' => true,
                    'enableClientValidation' => true,
                    'validateOnBlur' => false,
                ]);
                ?>

                <?php // Abandoned 2amigos/yii2-usuario core module `profile` fields ?>
                <?php //= $form->field($model, 'name') ?>
                <?php //= $form->field($model, 'website') ?>
                <?php //= $form->field($model, 'location') ?>
                <?php /* =
                  $form
                  ->field($model, 'timezone')
                  ->dropDownList(ArrayHelper::map($timezoneHelper->getAll(), 'timezone', 'name')); */
                ?>

                <h4>Profile Details</h4>
                <?= $form->field($model, 'public_email')->textInput(['readOnly' => true, 'disabled' => true]) ?>
                <?=
                $form->field($model, 'gravatar_email', [
                    'template' => "{label}\n<div class=\"col-sm-9\">{input}</div>\n<div class=\"col-sm-offset-3 col-sm-9\">{error}\n{hint}</div>"
                ])->hint(Html::a(Yii::t('usuario', 'Change your avatar at Gravatar.com'), 'http://gravatar.com', ['target' => '_blank']))
                ?>
                <?= $form->field($model, 'hs_salutation') ?>
                <?= $form->field($model, 'hs_firstname') ?>
                <?= $form->field($model, 'hs_lastname') ?>
                <?= $form->field($model, 'hs_jobtitle') ?>
                <?= $form->field($model, 'hs_mobile_phone') ?>
                <?= $form->field($model, 'hs_phone') ?>
                <?= $form->field($model, 'hs_fax') ?>
                <?= $form->field($model, 'website') ?>
                <?php //= $form->field($model, 'bio')->textarea() ?>

                <hr>
                
                <h4>Company &amp; Address Details</h4>
                <?= $form->field($model, 'hs_company') ?>
                <?= $form->field($model, 'hs_address_1') ?>
                <?= $form->field($model, 'hs_address_2') ?>
                <?= $form->field($model, 'hs_address_3') ?>
                <?= $form->field($model, 'hs_city') ?>
                <?= $form->field($model, 'hs_state') ?>
                <?= $form->field($model, 'hs_region')->dropDownList(Profile::addressRegionOptions(true), ['prompt' => 'Select Region']) ?>
                <?= $form->field($model, 'hs_zip') ?>
                <?= $form->field($model, 'hs_country') ?>

                <hr>
                
                <h4>Billing Contact</h4>
                <?= $form->field($model, 'hs_billing_contact')->checkbox() ?>
                <div id="billing_contact" <?= $model->hs_billing_contact ? 'style="display: none;"' : '' ?>>
                    <?= $form->field($model, 'billing_contact_firstname') ?>
                    <?= $form->field($model, 'billing_contact_lastname') ?>
                    <?= $form->field($model, 'billing_contact_email') ?>
                </div>
                
                <hr>
                
                <h4>Billing Address Details</h4>
                <?= $form->field($model, 'billing_address_same')->checkbox() ?>
                <div id="billing_address" <?= $model->billing_address_same ? 'style="display: none;"' : '' ?>>
                    <?= $form->field($model, 'billing_address_1') ?>
                    <?= $form->field($model, 'billing_address_2') ?>
                    <?= $form->field($model, 'billing_address_3') ?>
                    <?= $form->field($model, 'billing_city') ?>
                    <?= $form->field($model, 'billing_state') ?>
                    <?= $form->field($model, 'billing_region')->dropDownList(Profile::addressRegionOptions(true), ['prompt' => 'Select Region']) ?>
                    <?= $form->field($model, 'billing_zip') ?>
                    <?= $form->field($model, 'billing_country') ?>
                </div>

                <hr>

                <h4>Marketing Preferences</h4>
                <blockquote>
                    <p>&quot;<?= $model->getGdprText() ?>&quot;</p>
                </blockquote>
                <?= $form->field($model, 'gdpr_email')->checkbox() ?>
                <?= $form->field($model, 'gdpr_sms')->checkbox() ?>
                <?= $form->field($model, 'gdpr_phone')->checkbox() ?>
                <?= $form->field($model, 'gdpr_post')->checkbox() ?>
                <?= $form->field($model, 'gdpr_version', ['template' => '{input}', 'options' => ['tag' => false]])->hiddenInput(['value' => $model->getGdprTextVersion(), 'readonly' => true])->label(false) ?>
                <div class="form-group">
                    <div class="col-sm-offset-3 col-sm-9">
                        <span id="helpGDPR" class="help-block">Please tick all boxes where you give consent.</span>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-sm-offset-3 col-sm-9">
                        <?= Html::submitButton(Yii::t('usuario', 'Save'), ['class' => 'btn btn-block btn-success']) ?>
                        <br>
                    </div>
                </div>

                <?php ActiveForm::end(); ?>
            </div>
        </div>
    </div>
</div>